-- career_countries seed (auto-generated by scripts/parse-career-structured.mjs)
-- Idempotent: INSERT … ON CONFLICT (code) DO UPDATE

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('saudi-arabia', 'Saudi Arabia', 'Gulf', 'Employment visa; no PR pathway', 'Vision 2030 hospital + infrastructure expansion; oil & gas', 'None required', 'No', 'Largest OFW destination. Tax-free income + housing + annual flight. Use as stepping stone to Western countries.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('uae', 'UAE', 'Gulf', 'Employment visa; no PR pathway', 'Expo legacy; Abu Dhabi diversification; medical tourism; construction', 'None required', 'No', 'Dubai and Abu Dhabi. Fastest deployment (3-6 months most courses). High savings rate.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('qatar', 'Qatar', 'Gulf', 'Employment visa; no PR pathway', 'FIFA legacy infrastructure; QatarEnergy expansion; Lusail City', 'None required', 'No', 'Hamad Medical Corporation major employer. Post-FIFA construction continuing.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('kuwait', 'Kuwait', 'Gulf', 'Employment visa; no PR pathway', 'Healthcare expansion; oil & gas sector', 'None required', 'No', 'Smaller market. Healthcare professionals mainly.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('bahrain', 'Bahrain', 'Gulf', 'Employment visa; no PR pathway', 'Fintech hub; healthcare; real estate', 'None required', 'No', 'DIFC equivalent (BFSI) hub for finance professionals. Smaller market.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('uk', 'UK', 'Western Europe', 'Skilled Worker Visa / Health & Care Worker Visa ? ILR after 5 years', 'NHS workforce crisis; teacher shortage; SEND; social work shortage', 'IELTS 7.0-7.5 or OET Grade B', 'Yes (ILR ? Citizenship)', 'NHS is world''s largest recruiter of Filipino healthcare workers. QTS free from Aug 2025 for teachers.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('usa', 'USA', 'North America', 'H-1B / EB-2 / EB-3 ? Green Card', 'Healthcare shortage (AAMC 37k-124k physician gap); STEM shortage; SPED', 'English (CGFNS/IELTS varies)', 'Yes (Green Card)', 'Highest salary ceiling. H-1B lottery for engineers. EB-3 backlog 5-7yrs for nurses. EB-2 current for PH PTs/OTs.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('canada', 'Canada', 'North America', 'Express Entry ? PR (1-2 years); PNP streams', '500k immigrants/year target; healthcare worker shortage; infrastructure', 'IELTS 6.5-7.0 / CLB 8-9', 'Yes (PR ? Citizenship)', 'Fastest PR pathway in Western world. All provinces need healthcare workers and engineers.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('australia', 'Australia', 'Oceania', 'Skilled migration subclass 189/190/491 ? PR', 'Mining boom; healthcare shortage; infrastructure; NDIS disability', 'IELTS 6.0-7.5 (profession-specific)', 'Yes (PR ? Citizenship)', 'Critical minerals boom drives engineering demand. NDIS creates OT/allied health demand. NZ-adjacent lifestyle.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('new-zealand', 'New Zealand', 'Oceania', 'Green List (some direct PR); Skilled Migrant ? PR', 'Teacher shortage; healthcare; engineer shortage; primary industries', 'IELTS 6.5-7.0', 'Yes (PR ? Citizenship)', 'Green List gives fastest PR for shortage occupations (teachers, CE, nurses, vets). Excellent quality of life.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('germany', 'Germany', 'Western Europe', 'EU Blue Card ? PR (21-33 months) or Triple Win Nursing', '400k+ skilled worker shortage; EV sector; demographic aging', 'German B1 (Blue Card) or free via Triple Win (nurses)', 'Yes (PR ? Citizenship)', 'Nurses via Triple Win (free language training). Engineers via EU Blue Card. One of fastest EU PR pathways.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('ireland', 'Ireland', 'Western Europe', 'Critical Skills Employment Permit / General Employment Permit ? PR', 'NHS-adjacent nurse shortage; pharma manufacturing (Pfizer/J&J/Lilly); tech', 'IELTS 6.5-7.0', 'Yes (PR ? Citizenship)', 'EU passport after 5 years. Pharma manufacturing hub (MBB/Biochemistry). Growing healthcare demand.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('japan', 'Japan', 'East Asia', 'Engineer visa / SSW-i / EPA (nurses)', 'Super-aged society; semiconductor fab expansion; automation', 'Japanese N3-N2 (most roles); English OK at some tech companies', 'Yes (after 10 years; faster via HSP points)', '245,000+ Filipino workers (Oct 2024). Language is main barrier. SSW agriculture/hospitality accessible but lower pay.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('taiwan', 'Taiwan', 'East Asia', 'Employment Gold Card (professionals) or work permit', 'Semiconductor supercycle; TSMC/MediaTek fab expansion', 'English OK in Hsinchu tech corridor; Mandarin helpful', 'Possible (after 5 years)', 'Fastest-growing ECE/semiconductor destination. Mid-career $80k-$115k USD at TSMC/MediaTek.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('south-korea', 'South Korea', 'East Asia', 'E-7 professional visa', 'Samsung/SK Hynix semiconductor; Hyundai/Kia EV; K-drama content', 'Korean TOPIK helpful; English OK at Samsung/SK Hynix', 'Possible (F-2 ? F-5 after years)', 'KRW 102M avg (~$74k) for semiconductor engineers. Samsung aggressive international hiring.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('singapore', 'Singapore', 'Southeast Asia', 'Employment Pass (SGD 5,600/mo min) / S Pass', 'Regional financial hub; healthcare hub; AI/tech hub', 'English (Singapore uses English)', 'Possible (PR application)', 'ASEAN CPA/RFPA MRA active Jan 2025. AHPC for OTs. Highest cost of living but high salaries.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('norway', 'Norway', 'Northern Europe', 'Skilled worker permit ? PR (after 3 years)', 'North Sea oil; offshore wind; aluminum; salmon aquaculture', 'Norwegian B1 for career; English OK initially at international companies', 'Yes (after 3 years)', 'Highest paying destination for petroleum geologists ($125k avg) and metallurgical engineers ($83k-$120k). Offshore OSVs $10k-$18k/month.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('netherlands', 'Netherlands', 'Western Europe', 'EU Blue Card / DAFT ? PR', 'ASML (semiconductor lithography); logistics hub; Wageningen agribusiness', 'English (highly English-friendly)', 'Yes (PR ? Citizenship)', 'ASML in Eindhoven: world''s only EUV lithography manufacturer. Physics/ECE specialists in demand.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('israel', 'Israel', 'Middle East', 'Agricultural bilateral program / skilled worker', 'Agricultural technology; caregiver demand; high-tech', 'English + basic Hebrew helpful', 'Possible (after years)', 'Small bilateral program for agriculturists and caregivers. Israel is global AgTech leader.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('chile', 'Chile', 'South America', 'Work permit (relatively accessible) ? PR after 2 years', 'World''s largest copper producer; lithium mining (EV supply chain)', 'Spanish required', 'Yes', 'Codelco (world''s largest copper company). Metallurgical/mining engineers. Language barrier significant.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;

INSERT INTO career_countries (code, name, region, immigration_system, why_demand, language_required, pr_pathway, notes)
VALUES ('south-africa', 'South Africa', 'Africa', 'Critical Skills Work Visa', 'Gold/platinum/chrome mining; metallurgical engineering on critical skills list', 'English', 'Yes', 'Metallurgical engineers on critical skills list. Lower USD equivalent due to rand weakness.')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  immigration_system = EXCLUDED.immigration_system,
  why_demand = EXCLUDED.why_demand,
  language_required = EXCLUDED.language_required,
  pr_pathway = EXCLUDED.pr_pathway,
  notes = EXCLUDED.notes;
