-- career_programs seed (auto-generated by scripts/parse-career-structured.mjs)
-- Idempotent: INSERT … ON CONFLICT (id) DO UPDATE

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('nhs-international-recruitment', 'NHS International Recruitment', 'UK', ARRAY['Nursing', 'PT', 'OT', 'Radiographers', 'Pharmacists'], 'NHS Employers (UK) + POEA-accredited agencies', 'Unlimited (NHS-wide)', 'NMC/HCPC registration + IELTS 7.0/OET Grade B', 'Health and Care Worker Visa; reduced fee GBP 232; ILR after 5 yrs', 'nhsemployers.org', 'Employer sponsors directly. Some NHS trusts offer free accommodation first 3-6 months. CBT can be taken in Manila.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('triple-win-project-germany', 'Triple Win Project (Germany)', 'Germany', ARRAY['Nursing / Careworkers'], 'GIZ + Bundesagentur fuer Arbeit (BA/ZAV) + DMW Philippines', '~200-300/year from Philippines', 'B1 German (free training in PH); B2 in Germany (free)', 'Nursing Recognition Visa ? PR after 5 years (3 with integration)', 'triple-win-programm.de', 'Free language training. Salary EUR 2,907-3,629/month as nursing assistant; EUR 3,200-4,500 as licensed nurse. GIZ covers relocation costs.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('japan-epa-jpepa', 'Japan EPA (JPEPA)', 'Japan', ARRAY['Nursing (~50 slots)', 'Careworkers (~300 slots)'], 'JICWELS (Japan) + DMW Philippines', '~350/year total (PH allocation)', 'JLPT N3 minimum; 3-month language training in PH + 6-month in Japan', 'Up to 3 attempts at Japanese Nursing Board Exam over 3 years; no direct PR from EPA alone', 'jicwels.or.jp / dmw.gov.ph', 'Batch 17 recruitment: April 2026 deadline. Low board exam pass rate for foreign nurses (~30-50%). Yen weakness reduces USD value. Mainly cultural exchange + soft diplomacy.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('japan-ssw-i-specified-skilled-worker', 'Japan SSW-i (Specified Skilled Worker)', 'Japan', ARRAY['Agriculture', 'Food Service', 'Nursing care', 'Hospitality', 'Construction', 'Manufacturing', 'Fisheries', 'Shipbuilding'], 'JMHLW + POLO Manila', 'Varies by sector; thousands total', 'Skills test (in Japanese) + JLPT N4; no degree required for most categories', 'Up to 5 years total; SSW-ii (some sectors) has PR pathway', 'ssw.go.jp', 'Available for: Crop farming, livestock, food service, fishing. Degree not leveraged for most occupations. Agriculture SSW-i: JPY 170k-230k/month. Language is the primary barrier.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('asean-cpa-rfpa-mra', 'ASEAN CPA / RFPA MRA', 'ASEAN (Singapore, Thailand, Malaysia, Indonesia, Philippines, Vietnam, Myanmar, Cambodia, Laos, Brunei)', ARRAY['Accountancy / CPA'], 'ASEAN Chartered Professional Accountant (ASEAN CPA) Council / PICPA (Philippines)', 'Open (member country CPAs eligible)', 'PRC CPA license + 3 years experience + CPD compliance', 'Right to practice as Registered Foreign Professional Accountant (RFPA) in signatory countries', 'aseancpa.org', 'Activated January 31, 2025. Philippine CPAs can register as RFPA in Singapore (ISCA), Thailand, Malaysia, Indonesia. RFPA allows practice under supervision of local CPA; not full independent practice in all countries.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('us-cpa-exam-in-philippines-nasba', 'US CPA Exam in Philippines (NASBA)', 'USA', ARRAY['Accountancy / CPA'], 'NASBA (National Association of State Boards of Accountancy)', 'Open (eligible PH candidates)', 'Meets state CPA education requirements; states with no SSN needed: WI, NY, MT, IL, SD', 'US CPA license ? can work in USA under H-1B or employer-sponsored green card', 'nasba.org', 'Available in Philippines since July 1, 2024 — major policy change. PH candidates can now sit all 4 parts (FAR, AUD, REG, BEC/ISC/BAR) in Manila without traveling to USA.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('uk-qts-for-overseas-teachers', 'UK QTS for Overseas Teachers', 'UK', ARRAY['All teaching specializations (Secondary', 'Elementary', 'Early Childhood', 'SPED', 'Arts Education)'], 'UK Department for Education (DfE)', 'Open (eligible overseas teachers)', 'Recognized overseas qualification + 2 years teaching experience (from August 2025); IELTS 7.0', 'Qualified Teacher Status (QTS) ? can teach in UK state schools; Skilled Worker Visa', 'getintoteaching.education.gov.uk', 'FREE from August 2025 (previously GBP 255). iQTS route allows teacher training IN PHILIPPINES for UK recognition. Shortage subjects (Maths, Physics, Computing, MFL) get bursaries GBP 22k-29k.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('nz-green-list-teaching-engineering-healthcare', 'NZ Green List (Teaching + Engineering + Healthcare)', 'New Zealand', ARRAY['Secondary teachers', 'primary teachers', 'CE', 'GE', 'Social Workers', 'Veterinarians', 'RNs', 'others'], 'Immigration New Zealand', 'Open (eligible shortage occupations)', 'Country-specific registration + job offer + English', 'Tier 1: Straight to Residence (no work permit required). Tier 2: Work to Residence in 2 years.', 'immigration.govt.nz/new-zealand-visas/visas-by-situation/talent-and-skills/green-list-occupations', 'Updated March 2025. Secondary and primary teachers: Tier 2. Civil Engineers, Geodetic Engineers, Social Workers, Veterinarians also listed. Most direct PR pathway in the English-speaking world for these occupations.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('philippines-israel-agricultural-bilateral-program', 'Philippines-Israel Agricultural Bilateral Program', 'Israel', ARRAY['Agriculture (farm workers)'], 'POLO Israel + Israeli Ministry of Agriculture + OWWA', 'Limited (hundreds per year)', 'Physical fitness; basic English; no degree required', 'Work permit; renewable; no PR pathway', 'polo.dfa.gov.ph (Israel)', 'Contract-based work in greenhouse agriculture, poultry, irrigation. Better wage than Japan SSW (ILS 6,300-7,500/month ~$1,700-2,000 USD). Degree not leveraged at professional level.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('poea-standard-employment-contract-seafarers', 'POEA Standard Employment Contract (Seafarers)', 'Global (all flag states)', ARRAY['Merchant Marine (deck + engine officers', 'ratings)'], 'POEA/DMW + MARINA-licensed manning agencies', 'Unlimited (tens of thousands deployed annually)', 'MARINA COC + STCW + SIRB + GMDSS + medical certificate', 'Contract-based (usually 6-12 months); renewed per voyage; no PR', 'poea.gov.ph / marina.gov.ph', 'Mandatory OWWA coverage and allotment (80% remittance to PH family). OFW seafarers on international trade exempt from PH income tax. POEA deploys hundreds of thousands of seafarers annually.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('taiwan-employment-gold-card', 'Taiwan Employment Gold Card', 'Taiwan', ARRAY['ECE/Semiconductor engineers', 'scientists', 'IT specialists', 'artists'], 'National Development Council (NDC) Taiwan', 'Open (eligible professionals)', 'USD 5,000-10,000/month salary threshold OR recognized expertise', '3-year open work permit; can bring family; pathway to PR after 5 years', 'goldcard.nat.gov.tw', 'Targeted at global tech talent. Electronics/semiconductor engineers qualify if meeting salary threshold. No employer sponsor required - unprecedented flexibility.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('eu-blue-card', 'EU Blue Card', 'Germany, Netherlands, France, and most EU countries (not Denmark, Ireland)', ARRAY['Engineers', 'IT', 'Healthcare professionals', 'Scientists with university degree'], 'National immigration authorities of each EU country', 'Open (non-EU nationals with degree and job offer above salary threshold)', 'University degree + job offer above threshold (Germany: EUR 43,759 for shortage occupations 2025)', 'Possible PR after 21-33 months (Germany); varies by country', 'make-it-in-germany.com', 'Germany has fastest PR via Blue Card (21 months for German language integration; 33 months otherwise). ECE, ME, ChE, IE, CS all qualify. No separate language requirement if job contract is in English for initial Blue Card.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('adb-young-professionals-program', 'ADB Young Professionals Program', 'Philippines (Manila HQ) / ADB-wide', ARRAY['Economics', 'Finance', 'Development Studies', 'Environmental Science', 'Urban Planning'], 'Asian Development Bank (ADB) HQ Manila', '~25-30 positions/year globally', 'Master''s degree + under 32 years old + strong academic record', '2-year fixed-term staff contract; international salary (USD 70k-108k) + benefits tax-exempt in PH; pathway to regular ADB staff', 'adb.org/careers', 'Manila-based but international salary and career. ADB has 68 member countries. PH nationals have natural advantage. Development economics/finance/infrastructure focus.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;

INSERT INTO career_programs (id, name, country_region, courses_covered, managing_body, slots, requirements, immigration_outcome, website, notes)
VALUES ('green-climate-fund-gcf-positions', 'Green Climate Fund (GCF) Positions', 'South Korea (Songdo/Incheon)', ARRAY['Climate Change', 'Environmental Science', 'Economics', 'Engineering', 'Finance'], 'Green Climate Fund Secretariat', '~50-100 new positions/year', 'Bachelor''s degree minimum; relevant experience; English; second language advantageous', 'International civil servant contract; PR possible after years of Korean residence', 'greenclimate.fund', 'Philippines as developing country party has competitive advantage in hiring. ESG/climate finance roles. Tax-exempt international salary. Korea E-7 visa for GCF staff.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  country_region = EXCLUDED.country_region,
  courses_covered = EXCLUDED.courses_covered,
  managing_body = EXCLUDED.managing_body,
  slots = EXCLUDED.slots,
  requirements = EXCLUDED.requirements,
  immigration_outcome = EXCLUDED.immigration_outcome,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes;
