#!/usr/bin/env node
/**
 * Fetches DepEd SHS school list and generates:
 *   scripts/schools-data.json   — for reference
 *   supabase/migrations/008_schools.sql — ready to apply
 *
 * Usage:
 *   node scripts/scrape-schools.js               # fetch from DepEd
 *   node scripts/scrape-schools.js --input <file> # parse local .xlsx or .html
 */

const fs = require('fs')
const path = require('path')

const DEPED_URL = 'https://www.deped.gov.ph/k-to-12/senior-high-school/list-of-senior-high-schools/'

const REGION_ALIASES = {
  // NCR
  'national capital region': 'NCR',
  'ncr': 'NCR',
  'metro manila': 'NCR',
  // CAR
  'cordillera administrative region': 'CAR',
  'car': 'CAR',
  // Region I
  'region i': 'Region I - Ilocos Region',
  'region i - ilocos region': 'Region I - Ilocos Region',
  'ilocos region': 'Region I - Ilocos Region',
  // Region II
  'region ii': 'Region II - Cagayan Valley',
  'region ii - cagayan valley': 'Region II - Cagayan Valley',
  'cagayan valley': 'Region II - Cagayan Valley',
  // Region III
  'region iii': 'Region III - Central Luzon',
  'region iii - central luzon': 'Region III - Central Luzon',
  'central luzon': 'Region III - Central Luzon',
  // Region IV-A
  'region iv-a': 'Region IV-A - CALABARZON',
  'region iv-a - calabarzon': 'Region IV-A - CALABARZON',
  'calabarzon': 'Region IV-A - CALABARZON',
  // Region IV-B
  'region iv-b': 'Region IV-B - MIMAROPA',
  'region iv-b - mimaropa': 'Region IV-B - MIMAROPA',
  'mimaropa': 'Region IV-B - MIMAROPA',
  // Region V
  'region v': 'Region V - Bicol Region',
  'region v - bicol region': 'Region V - Bicol Region',
  'bicol region': 'Region V - Bicol Region',
  // Region VI
  'region vi': 'Region VI - Western Visayas',
  'region vi - western visayas': 'Region VI - Western Visayas',
  'western visayas': 'Region VI - Western Visayas',
  // Region VII
  'region vii': 'Region VII - Central Visayas',
  'region vii - central visayas': 'Region VII - Central Visayas',
  'central visayas': 'Region VII - Central Visayas',
  // Region VIII
  'region viii': 'Region VIII - Eastern Visayas',
  'region viii - eastern visayas': 'Region VIII - Eastern Visayas',
  'eastern visayas': 'Region VIII - Eastern Visayas',
  // Region IX
  'region ix': 'Region IX - Zamboanga Peninsula',
  'region ix - zamboanga peninsula': 'Region IX - Zamboanga Peninsula',
  'zamboanga peninsula': 'Region IX - Zamboanga Peninsula',
  // Region X
  'region x': 'Region X - Northern Mindanao',
  'region x - northern mindanao': 'Region X - Northern Mindanao',
  'northern mindanao': 'Region X - Northern Mindanao',
  // Region XI
  'region xi': 'Region XI - Davao Region',
  'region xi - davao region': 'Region XI - Davao Region',
  'davao region': 'Region XI - Davao Region',
  // Region XII
  'region xii': 'Region XII - SOCCSKSARGEN',
  'region xii - soccsksargen': 'Region XII - SOCCSKSARGEN',
  'soccsksargen': 'Region XII - SOCCSKSARGEN',
  // Region XIII / CARAGA
  'region xiii': 'Region XIII - Caraga',
  'region xiii - caraga': 'Region XIII - Caraga',
  'caraga': 'Region XIII - Caraga',
  // BARMM / ARMM
  'barmm': 'BARMM',
  'bangsamoro autonomous region in muslim mindanao': 'BARMM',
  'armm': 'BARMM',
  // NIR - Negros Island Region
  'nir': 'NIR - Negros Island Region',
  'negros island region': 'NIR - Negros Island Region',
  // Overseas (Philippine schools abroad)
  'middle east': 'Overseas - Middle East',
  'europe': 'Overseas - Europe',
  'asia': 'Overseas - Asia',
  'americas': 'Overseas - Americas',
}

function normaliseRegion(raw) {
  const key = (raw ?? '').toLowerCase().trim()
  return REGION_ALIASES[key] ?? raw.trim()
}

function escSql(str) {
  return (str ?? '').replace(/'/g, "''")
}

function parseRow(obj) {
  const region = normaliseRegion(
    obj['Region'] ?? obj['region'] ?? obj['REGION'] ?? ''
  )
  const province = (
    obj['Division'] ?? obj['division'] ?? obj['Province'] ?? obj['province'] ??
    obj['DIVISION'] ?? obj['PROVINCE'] ?? ''
  ).trim()
  const city = (
    obj['Municipality'] ?? obj['municipality'] ?? obj['City'] ?? obj['city'] ??
    obj['MUNICIPALITY'] ?? obj['CITY/MUNICIPALITY'] ?? ''
  ).trim()
  const name = (
    obj['School Name'] ?? obj['school_name'] ?? obj['Name'] ?? obj['name'] ??
    obj['SCHOOL NAME'] ?? obj['SCHOOLNAME'] ?? ''
  ).trim()
  const depedId = String(
    obj['School ID'] ?? obj['school_id'] ?? obj['ID'] ?? obj['SCHOOL ID'] ?? ''
  ).trim()

  if (!region || !name) return null
  return {
    region,
    province: province || region,
    city: city || province || region,
    name,
    deped_id: depedId || null,
  }
}

function generateSql(schools) {
  const regions = [...new Set(schools.map(s => s.region))].sort()

  const ddl = `-- Auto-generated by scripts/scrape-schools.js on ${new Date().toISOString().slice(0, 10)}
-- DO NOT edit by hand — re-run the scraper to regenerate

CREATE TABLE IF NOT EXISTS schools (
  id SERIAL PRIMARY KEY,
  region TEXT NOT NULL,
  province TEXT NOT NULL,
  city TEXT NOT NULL,
  name TEXT NOT NULL,
  deped_id TEXT
);

CREATE INDEX IF NOT EXISTS schools_region_idx ON schools(region);
CREATE INDEX IF NOT EXISTS schools_province_idx ON schools(province);
CREATE INDEX IF NOT EXISTS schools_city_idx ON schools(city);

ALTER TABLE schools ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='schools' AND policyname='schools_public_read') THEN
    CREATE POLICY "schools_public_read" ON schools FOR SELECT USING (true);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS school_regions (
  region TEXT PRIMARY KEY
);

ALTER TABLE school_regions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='school_regions' AND policyname='school_regions_public_read') THEN
    CREATE POLICY "school_regions_public_read" ON school_regions FOR SELECT USING (true);
  END IF;
END $$;

`

  const chunks = []
  for (let i = 0; i < schools.length; i += 500) {
    const batch = schools.slice(i, i + 500)
    const values = batch
      .map(s => `('${escSql(s.region)}','${escSql(s.province)}','${escSql(s.city)}','${escSql(s.name)}',${s.deped_id ? `'${escSql(s.deped_id)}'` : 'NULL'})`)
      .join(',\n  ')
    chunks.push(`INSERT INTO schools (region, province, city, name, deped_id) VALUES\n  ${values}\nON CONFLICT DO NOTHING;`)
  }

  const regionInserts = regions
    .map(r => `('${escSql(r)}')`)
    .join(',\n  ')
  const regionSql = `\n-- Region lookup table\nINSERT INTO school_regions (region) VALUES\n  ${regionInserts}\nON CONFLICT DO NOTHING;\n`

  return ddl + chunks.join('\n\n') + regionSql
}

async function parseXlsx(buffer) {
  const XLSX = require('xlsx')
  const wb = XLSX.read(buffer, { type: 'buffer' })
  const sheetName = wb.SheetNames[0]
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[sheetName], { defval: '' })
  return rows.map(parseRow).filter(Boolean)
}

async function parseHtml(html) {
  const cheerio = require('cheerio')
  const $ = cheerio.load(html)
  const schools = []

  // The DepEd page has multiple tables (one per region group).
  // Each table (except the first legend table) has columns:
  //   TAXONOMY (Region|Province), MUNICIPALITY, SCHOOL ID, SCHOOL NAME, PROGRAM OFFERINGS
  // Skip header rows (th cells or rows where first cell is 'TAXONOMY')
  $('table').each((tIdx, table) => {
    $(table).find('tr').each((_, tr) => {
      const cells = $(tr).find('td').map((_, td) => $(td).text().trim()).get()
      if (cells.length < 4) return
      // Skip header rows
      if (cells[0].toUpperCase() === 'TAXONOMY') return

      const taxonomy = cells[0] // e.g. "NCR|Metro Manila" or "Region I|Ilocos Norte"
      const municipality = cells[1] ?? ''
      const schoolId = cells[2] ?? ''
      const schoolName = cells[3] ?? ''

      // Split taxonomy into region and province
      const pipeIdx = taxonomy.indexOf('|')
      let rawRegion, rawProvince
      if (pipeIdx !== -1) {
        rawRegion = taxonomy.slice(0, pipeIdx).trim()
        rawProvince = taxonomy.slice(pipeIdx + 1).trim()
      } else {
        rawRegion = taxonomy.trim()
        rawProvince = taxonomy.trim()
      }

      const region = normaliseRegion(rawRegion)
      const province = rawProvince || region
      const city = municipality.trim() || province
      const name = schoolName.trim()
      const deped_id = schoolId.trim() || null

      if (!region || !name) return
      // Skip legend/header rows — valid regions contain Roman numerals, NCR, CAR, BARMM, NIR, or Overseas
      const validRegionPattern = /^(NCR|CAR|BARMM|NIR|Overseas|Region (I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII|XIII))/i
      if (!validRegionPattern.test(region)) return
      schools.push({ region, province, city, name, deped_id })
    })
  })
  return schools
}

async function fetchAndParse(inputPath) {
  if (inputPath) {
    console.log(`Reading local file: ${inputPath}`)
    const buf = fs.readFileSync(inputPath)
    if (inputPath.endsWith('.xlsx') || inputPath.endsWith('.xls')) {
      return parseXlsx(buf)
    }
    return parseHtml(buf.toString('utf8'))
  }

  console.log(`Fetching ${DEPED_URL}`)
  const res = await fetch(DEPED_URL, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; Iskotify-scraper/1.0)' },
  })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)

  const html = await res.text()
  const cheerio = require('cheerio')
  const $ = cheerio.load(html)
  const xlsxLink = $('a[href$=".xlsx"], a[href$=".xls"]').first().attr('href')

  if (xlsxLink) {
    const absUrl = xlsxLink.startsWith('http') ? xlsxLink : new URL(xlsxLink, DEPED_URL).href
    console.log(`Found Excel file: ${absUrl}`)
    const xlsRes = await fetch(absUrl, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; Iskotify-scraper/1.0)' },
    })
    if (!xlsRes.ok) throw new Error(`Excel download failed: HTTP ${xlsRes.status}`)
    const buf = Buffer.from(await xlsRes.arrayBuffer())
    return parseXlsx(buf)
  }

  console.log('No Excel link found — parsing HTML table')
  return parseHtml(html)
}

async function main() {
  const inputFlag = process.argv.indexOf('--input')
  const inputPath = inputFlag !== -1 ? process.argv[inputFlag + 1] : null

  let schools
  try {
    schools = await fetchAndParse(inputPath)
  } catch (err) {
    console.error('Scrape failed:', err.message)
    console.error(
      '\nFallback: download the DepEd Excel file manually from:\n' +
      DEPED_URL +
      '\nthen run: node scripts/scrape-schools.js --input <downloaded-file.xlsx>'
    )
    process.exit(1)
  }

  if (schools.length === 0) {
    console.error('No schools parsed — check the DepEd page format has changed.')
    process.exit(1)
  }

  console.log(`Parsed ${schools.length} schools across ${new Set(schools.map(s => s.region)).size} regions`)

  const jsonPath = path.join(__dirname, 'schools-data.json')
  const sqlPath = path.join(__dirname, '..', 'supabase', 'migrations', '008_schools.sql')

  fs.writeFileSync(jsonPath, JSON.stringify(schools, null, 2))
  console.log(`Written: ${jsonPath}`)

  fs.writeFileSync(sqlPath, generateSql(schools))
  console.log(`Written: ${sqlPath}`)
}

main()

module.exports = { normaliseRegion, parseRow, generateSql, escSql }
