-- Seed the ACET "General Information" question pool (acet:4 section, 65 items,
-- added in 045_exam_blueprint_fixes.sql). Without these rows the section has
-- zero published questions and the mobile exam builder renders "Content
-- coming soon" for that block.
--
-- Rows are standalone (set_id NULL) so passage-linked builders that filter out
-- reading-set questions still see them. skill_category = 'General Information'
-- is what the ACET blueprint engine (getQuestionsByCategory in
-- apps/mobile/services/examBlueprints.ts) filters on; subtest and main_subject
-- are set to the same label for consistency with the rest of the bank.
-- status = 'published' matches the only status value the app's sync/queries
-- surface (see project_question_bank_to_flashcards() in
-- 026_project_question_bank.sql and getQuestionsByCategory).
--
-- Content: stable, textbook-verifiable Philippine and world general-knowledge
-- facts only (history, 1987 Constitution structure, geography, culture,
-- founding facts of the UN/ASEAN, basic science). No current officeholders,
-- no current events, no population figures or rankings that change, nothing
-- dated after 2020. Idempotent via ON CONFLICT (question_id) DO NOTHING.

INSERT INTO upcat_questions
  (question_id, subtest, main_subject, topic, skill_category, question_text, options, correct_index, explanation, set_id, status)
VALUES
  -- Philippine History (GI001-GI015)
  ('GI001','General Information','General Information','Philippine History','General Information','Which Filipino is officially recognized in Philippine history textbooks as the country''s national hero?',ARRAY['Andres Bonifacio','Jose Rizal','Emilio Aguinaldo','Apolinario Mabini'],1,'Jose Rizal, executed in 1896, is honored as the national hero of the Philippines for writings that inspired the reform and independence movements.',NULL,'published'),
  ('GI002','General Information','General Information','Philippine History','General Information','Which of Jose Rizal''s two famous novels was published first?',ARRAY['El Filibusterismo','Noli Me Tangere','Mi Ultimo Adios','Sa Aking Mga Kabata'],1,'Noli Me Tangere was published in 1887, four years before its sequel El Filibusterismo in 1891.',NULL,'published'),
  ('GI003','General Information','General Information','Philippine History','General Information','Who founded the Katipunan, the secret society that launched the 1896 Philippine Revolution?',ARRAY['Andres Bonifacio','Jose Rizal','Marcelo del Pilar','Graciano Lopez Jaena'],0,'Andres Bonifacio founded the Katipunan in 1892 to organize an armed revolution against Spanish rule.',NULL,'published'),
  ('GI004','General Information','General Information','Philippine History','General Information','Which Filipino chieftain defeated and killed Ferdinand Magellan at the Battle of Mactan in 1521?',ARRAY['Rajah Humabon','Lapu-Lapu','Rajah Sulayman','Datu Puti'],1,'Lapu-Lapu, chieftain of Mactan, led local warriors who repelled Magellan''s Spanish forces and killed Magellan in 1521.',NULL,'published'),
  ('GI005','General Information','General Information','Philippine History','General Information','Who served as the first President of the Philippines under the short-lived Malolos Republic?',ARRAY['Manuel L. Quezon','Emilio Aguinaldo','Andres Bonifacio','Sergio Osmena'],1,'Emilio Aguinaldo was inaugurated president of the First Philippine Republic (Malolos Republic) in January 1899.',NULL,'published'),
  ('GI006','General Information','General Information','Philippine History','General Information','In which town was Philippine independence from Spain declared on June 12, 1898?',ARRAY['Malolos, Bulacan','Kawit, Cavite','Baler, Aurora','Balintawak, Quezon City'],1,'Emilio Aguinaldo declared independence at his ancestral home in Kawit, Cavite on June 12, 1898.',NULL,'published'),
  ('GI007','General Information','General Information','Philippine History','General Information','Which country ruled the Philippines as a colony for over three centuries before the Spanish-American War?',ARRAY['Portugal','The Netherlands','Spain','Great Britain'],2,'Spain colonized the Philippines from 1565, when Miguel Lopez de Legazpi established a settlement in Cebu, until 1898.',NULL,'published'),
  ('GI008','General Information','General Information','Philippine History','General Information','Which 1898 treaty ended the Spanish-American War and ceded the Philippines to the United States?',ARRAY['Treaty of Versailles','Treaty of Paris','Treaty of Tordesillas','Treaty of Manila'],1,'The Treaty of Paris, signed in December 1898, ended the Spanish-American War and transferred control of the Philippines to the United States.',NULL,'published'),
  ('GI009','General Information','General Information','Philippine History','General Information','On what date did the Philippines gain full independence from the United States?',ARRAY['June 12, 1898','July 4, 1946','August 21, 1983','February 25, 1986'],1,'The United States formally recognized Philippine independence on July 4, 1946, under the Treaty of Manila.',NULL,'published'),
  ('GI010','General Information','General Information','Philippine History','General Information','Who was the first President of the Commonwealth of the Philippines, established in 1935?',ARRAY['Manuel L. Quezon','Manuel Roxas','Sergio Osmena','Jose P. Laurel'],0,'Manuel L. Quezon was inaugurated as the first President of the Commonwealth of the Philippines in 1935.',NULL,'published'),
  ('GI011','General Information','General Information','Philippine History','General Information','In what year did the EDSA People Power Revolution take place, ousting President Ferdinand Marcos?',ARRAY['1972','1981','1986','1992'],2,'The peaceful EDSA People Power Revolution in February 1986 ended the Marcos presidency and installed Corazon Aquino.',NULL,'published'),
  ('GI012','General Information','General Information','Philippine History','General Information','Who became the Philippines'' first female President in 1986?',ARRAY['Gloria Macapagal-Arroyo','Miriam Defensor Santiago','Corazon Aquino','Imelda Marcos'],2,'Corazon Aquino became the country''s first female president following the 1986 EDSA People Power Revolution.',NULL,'published'),
  ('GI013','General Information','General Information','Philippine History','General Information','The Bataan Death March, a forced transfer of prisoners of war, took place in which year during World War II?',ARRAY['1941','1942','1944','1945'],1,'After the fall of Bataan in April 1942, Filipino and American prisoners of war were forced on the brutal march now known as the Bataan Death March.',NULL,'published'),
  ('GI014','General Information','General Information','Philippine History','General Information','Which country occupied the Philippines from 1942 to 1945 during World War II?',ARRAY['Germany','Japan','Great Britain','Italy'],1,'Imperial Japan occupied the Philippines from 1942 until its liberation by combined Filipino and American forces in 1945.',NULL,'published'),
  ('GI015','General Information','General Information','Philippine History','General Information','Where was Jose Rizal executed by firing squad on December 30, 1896?',ARRAY['Fort Santiago','Bagumbayan (present-day Rizal Park)','Corregidor','Intramuros Cathedral'],1,'Rizal was executed by firing squad at Bagumbayan field, now Rizal Park (Luneta), in Manila.',NULL,'published'),

  -- Philippine Government and Constitution (GI016-GI030)
  ('GI016','General Information','General Information','Philippine Government','General Information','What is the supreme law of the land currently in force in the Philippines?',ARRAY['The 1935 Constitution','The 1973 Constitution','The 1987 Constitution','The Malolos Constitution'],2,'The 1987 Constitution, ratified after the EDSA Revolution, is the current supreme law of the Philippines.',NULL,'published'),
  ('GI017','General Information','General Information','Philippine Government','General Information','The Philippine government is divided into which three branches?',ARRAY['Executive, Legislative, Judicial','Federal, State, Local','National, Regional, Municipal','Civil, Military, Religious'],0,'Like most republics, the Philippines separates power among the Executive, Legislative, and Judicial branches.',NULL,'published'),
  ('GI018','General Information','General Information','Philippine Government','General Information','The Philippine Congress is bicameral, meaning it is composed of which two chambers?',ARRAY['Senate and House of Representatives','Senate and Cabinet','House of Representatives and Supreme Court','Senate and Sangguniang Bayan'],0,'The 1987 Constitution establishes a bicameral Congress made up of the Senate and the House of Representatives.',NULL,'published'),
  ('GI019','General Information','General Information','Philippine Government','General Information','How long is the term of the President of the Philippines, and how many terms may one serve?',ARRAY['4 years, up to two terms','6 years, a single term only','6 years, up to two terms','5 years, unlimited terms'],1,'The President serves a single six-year term and is constitutionally barred from reelection.',NULL,'published'),
  ('GI020','General Information','General Information','Philippine Government','General Information','How many members make up the Philippine Senate?',ARRAY['12','24','50','100'],1,'The Senate is composed of 24 senators elected at large.',NULL,'published'),
  ('GI021','General Information','General Information','Philippine Government','General Information','What is the term length of a Philippine senator, and how many consecutive terms may they serve?',ARRAY['3 years, up to three terms','6 years, up to two consecutive terms','6 years, unlimited terms','4 years, up to two terms'],1,'Senators serve six-year terms and may not serve more than two consecutive terms.',NULL,'published'),
  ('GI022','General Information','General Information','Philippine Government','General Information','What is the term length of a member of the House of Representatives, and how many consecutive terms may they serve?',ARRAY['3 years, up to three consecutive terms','6 years, up to two consecutive terms','4 years, up to two consecutive terms','2 years, unlimited terms'],0,'Members of the House of Representatives serve three-year terms and may not serve more than three consecutive terms.',NULL,'published'),
  ('GI023','General Information','General Information','Philippine Government','General Information','What is the highest court in the Philippine judicial system?',ARRAY['Court of Appeals','Sandiganbayan','Supreme Court','Regional Trial Court'],2,'The Supreme Court is the court of last resort and the highest tribunal in the Philippines.',NULL,'published'),
  ('GI024','General Information','General Information','Philippine Government','General Information','How many justices, including the Chief Justice, sit on the Philippine Supreme Court?',ARRAY['9','12','15','21'],2,'The Supreme Court is composed of a Chief Justice and 14 Associate Justices, for a total of 15.',NULL,'published'),
  ('GI025','General Information','General Information','Philippine Government','General Information','Who appoints the Justices of the Supreme Court in the Philippines?',ARRAY['The Senate','The President, from a list submitted by the Judicial and Bar Council','The Chief Justice','The House of Representatives'],1,'The President appoints Supreme Court Justices from nominees screened and shortlisted by the Judicial and Bar Council.',NULL,'published'),
  ('GI026','General Information','General Information','Philippine Government','General Information','Under the 1987 Constitution, how many successive terms may a Vice President serve?',ARRAY['Only one term','No more than two successive terms','Unlimited terms','No more than three successive terms'],1,'The Constitution allows the Vice President to serve, at most, two successive terms.',NULL,'published'),
  ('GI027','General Information','General Information','Philippine Government','General Information','What is the smallest and most basic local government unit in the Philippines?',ARRAY['Municipality','Province','Barangay','City'],2,'The barangay is the smallest political unit in the Philippine local government structure.',NULL,'published'),
  ('GI028','General Information','General Information','Philippine Government','General Information','What is the minimum age requirement to vote in Philippine elections?',ARRAY['15 years old','18 years old','21 years old','25 years old'],1,'The Constitution sets the minimum voting age at 18 years old for all qualified citizens.',NULL,'published'),
  ('GI029','General Information','General Information','Philippine Government','General Information','According to the 1987 Constitution, what are the official languages of the Philippines for purposes of communication and instruction?',ARRAY['Filipino only','English only','Filipino and English','Filipino, English, and Spanish'],2,'Article XIV designates Filipino as the national language, with Filipino and English as official languages for communication and instruction.',NULL,'published'),
  ('GI030','General Information','General Information','Philippine Government','General Information','Which chamber of Congress has the exclusive power to initiate impeachment cases against high officials?',ARRAY['The Senate','The House of Representatives','The Supreme Court','The Office of the Ombudsman'],1,'The House of Representatives has the exclusive power to initiate impeachment complaints, while the Senate has the sole power to try and decide them.',NULL,'published'),

  -- Geography (GI031-GI040)
  ('GI031','General Information','General Information','Geography','General Information','Which is the largest island in the Philippine archipelago?',ARRAY['Mindanao','Luzon','Palawan','Panay'],1,'Luzon is the largest and most populous island in the Philippines.',NULL,'published'),
  ('GI032','General Information','General Information','Geography','General Information','Which is the second-largest island in the Philippines?',ARRAY['Luzon','Samar','Mindanao','Negros'],2,'Mindanao is the second-largest island in the Philippine archipelago, after Luzon.',NULL,'published'),
  ('GI033','General Information','General Information','Geography','General Information','The Philippine archipelago is traditionally divided into which three main island groups?',ARRAY['Luzon, Visayas, Mindanao','North, Central, South','Tagalog, Visayan, Moro','Palawan, Sulu, Batanes'],0,'The Philippines is traditionally grouped into Luzon, Visayas, and Mindanao.',NULL,'published'),
  ('GI034','General Information','General Information','Geography','General Information','What is the highest mountain in the Philippines?',ARRAY['Mount Pinatubo','Mount Mayon','Mount Apo','Mount Pulag'],2,'Mount Apo, located in Mindanao, is the highest mountain peak in the Philippines.',NULL,'published'),
  ('GI035','General Information','General Information','Geography','General Information','What is the capital city of the Philippines?',ARRAY['Quezon City','Manila','Cebu City','Davao City'],1,'Manila is the capital city of the Philippines, seated within the larger Metro Manila region.',NULL,'published'),
  ('GI036','General Information','General Information','Geography','General Information','What is the largest lake in the Philippines?',ARRAY['Lake Lanao','Taal Lake','Laguna de Bay','Lake Mainit'],2,'Laguna de Bay, near Metro Manila, is the largest lake in the Philippines.',NULL,'published'),
  ('GI037','General Information','General Information','Geography','General Information','Which river is regarded as the longest river in the Philippines?',ARRAY['Pasig River','Agno River','Cagayan River','Bicol River'],2,'The Cagayan River (Rio Grande de Cagayan), flowing through the Cagayan Valley, is the longest river in the Philippines.',NULL,'published'),
  ('GI038','General Information','General Information','Geography','General Information','Which ocean lies to the east of the Philippine archipelago?',ARRAY['Indian Ocean','Atlantic Ocean','Pacific Ocean','Arctic Ocean'],2,'The Pacific Ocean borders the Philippines to the east.',NULL,'published'),
  ('GI039','General Information','General Information','Geography','General Information','Which body of water lies to the west of the Philippines and includes the area the Philippines calls the West Philippine Sea?',ARRAY['South China Sea','Sulu Sea','Celebes Sea','Bay of Bengal'],0,'The South China Sea borders the Philippines to the west; the Philippines refers to its portion of these waters as the West Philippine Sea.',NULL,'published'),
  ('GI040','General Information','General Information','Geography','General Information','The Philippines lies along which major seismic and volcanic belt?',ARRAY['The Great Rift Valley','The Pacific Ring of Fire','The Alpine Belt','The Mid-Atlantic Ridge'],1,'The Philippines sits along the Pacific Ring of Fire, making it prone to earthquakes and volcanic activity.',NULL,'published'),

  -- Culture, Arts, and Literature (GI041-GI050)
  ('GI041','General Information','General Information','Culture and Arts','General Information','What is the national language of the Philippines as designated by the Constitution?',ARRAY['Cebuano','Filipino','Spanish','Ilocano'],1,'The 1987 Constitution designates Filipino as the national language of the Philippines.',NULL,'published'),
  ('GI042','General Information','General Information','Culture and Arts','General Information','What is the national flower of the Philippines?',ARRAY['Rose','Sampaguita','Gumamela','Waling-waling'],1,'The sampaguita, a small fragrant white flower, is the national flower of the Philippines.',NULL,'published'),
  ('GI043','General Information','General Information','Culture and Arts','General Information','What is the national tree of the Philippines?',ARRAY['Narra','Acacia','Mahogany','Bamboo'],0,'The narra tree is officially designated as the national tree of the Philippines.',NULL,'published'),
  ('GI044','General Information','General Information','Culture and Arts','General Information','What is the national bird of the Philippines?',ARRAY['Maya bird','Philippine Eagle','Kalaw (hornbill)','Tarictic'],1,'The Philippine Eagle, one of the largest eagles in the world, is the national bird of the Philippines.',NULL,'published'),
  ('GI045','General Information','General Information','Culture and Arts','General Information','Which Philippine folk dance, in which dancers step between clashing bamboo poles, is widely regarded as the country''s national dance?',ARRAY['Tinikling','Carinosa','Pandanggo sa Ilaw','Sayaw sa Bangko'],0,'Tinikling, danced between rhythmically clashing bamboo poles, is the folk dance most widely recognized as representative of the Philippines.',NULL,'published'),
  ('GI046','General Information','General Information','Culture and Arts','General Information','Who wrote the epic poem Florante at Laura and is regarded as the father of Filipino poetry?',ARRAY['Francisco Balagtas','Jose Rizal','Andres Bonifacio','Marcelo del Pilar'],0,'Francisco Balagtas wrote Florante at Laura and is honored as the father of Filipino poetry, sometimes called the Prince of Tagalog Poets.',NULL,'published'),
  ('GI047','General Information','General Information','Culture and Arts','General Information','Which martial art was declared the national martial art and national sport of the Philippines by Republic Act No. 9850?',ARRAY['Judo','Arnis','Taekwondo','Boxing'],1,'Republic Act No. 9850, signed in 2009, declared Arnis (also called Eskrima or Kali) the national martial art and sport of the Philippines.',NULL,'published'),
  ('GI048','General Information','General Information','Culture and Arts','General Information','What is the traditional formal attire worn by Filipino men, often made of pina or jusi fabric?',ARRAY['Terno','Barong Tagalog','Malong','Baro''t Saya'],1,'The Barong Tagalog is the traditional embroidered formal shirt worn by Filipino men.',NULL,'published'),
  ('GI049','General Information','General Information','Culture and Arts','General Information','What is the traditional Filipino house built on stilts, typically made of bamboo and nipa (thatched palm leaves)?',ARRAY['Bahay Kubo','Bahay na Bato','Torogan','Ifugao Hut'],0,'The Bahay Kubo, or nipa hut, is the traditional stilt house made of bamboo and nipa thatch found across the Philippine countryside.',NULL,'published'),
  ('GI050','General Information','General Information','Culture and Arts','General Information','Which major festival, held every January in Cebu City, honors the Santo Nino?',ARRAY['Ati-Atihan Festival','Pahiyas Festival','Sinulog Festival','MassKara Festival'],2,'The Sinulog Festival in Cebu City is a religious and cultural celebration honoring the Santo Nino (Holy Child Jesus).',NULL,'published'),

  -- World Geography (GI051-GI054)
  ('GI051','General Information','General Information','World Facts','General Information','Which is the largest continent on Earth by land area?',ARRAY['Africa','Asia','North America','Europe'],1,'Asia is the largest continent in the world by both land area and population.',NULL,'published'),
  ('GI052','General Information','General Information','World Facts','General Information','Which is the largest ocean on Earth?',ARRAY['Atlantic Ocean','Indian Ocean','Pacific Ocean','Arctic Ocean'],2,'The Pacific Ocean is the largest and deepest of the world''s oceans.',NULL,'published'),
  ('GI053','General Information','General Information','World Facts','General Information','Which is the smallest of the world''s oceans?',ARRAY['Arctic Ocean','Indian Ocean','Southern Ocean','Atlantic Ocean'],0,'The Arctic Ocean is the smallest and shallowest of the world''s five oceans.',NULL,'published'),
  ('GI054','General Information','General Information','World Facts','General Information','The Nile River, flowing through northeastern Africa, is traditionally taught in geography classes as which of the following?',ARRAY['The widest river in the world','The longest river in the world','The deepest river in the world','The fastest-flowing river in the world'],1,'The Nile River is traditionally cited in geography lessons as the longest river in the world.',NULL,'published'),

  -- World / Current Institutions (GI055-GI058)
  ('GI055','General Information','General Information','Current Institutions','General Information','In what year was the United Nations founded?',ARRAY['1919','1945','1957','1967'],1,'The United Nations was founded in 1945, after World War II, to promote international peace and cooperation.',NULL,'published'),
  ('GI056','General Information','General Information','Current Institutions','General Information','In which city is the headquarters of the United Nations located?',ARRAY['Geneva','Brussels','New York City','The Hague'],2,'The United Nations headquarters is located in New York City, United States.',NULL,'published'),
  ('GI057','General Information','General Information','Current Institutions','General Information','In what year was the Association of Southeast Asian Nations (ASEAN) founded?',ARRAY['1954','1967','1975','1989'],1,'ASEAN was founded on August 8, 1967, through the Bangkok Declaration.',NULL,'published'),
  ('GI058','General Information','General Information','Current Institutions','General Information','The Philippines was one of how many founding member countries of ASEAN in 1967?',ARRAY['Three','Five','Seven','Ten'],1,'ASEAN was founded by five countries in 1967: Indonesia, Malaysia, the Philippines, Singapore, and Thailand.',NULL,'published'),

  -- General Science and Technology Awareness (GI059-GI065)
  ('GI059','General Information','General Information','General Science','General Information','What is the chemical formula for water?',ARRAY['CO2','H2O','O2','NaCl'],1,'Water is composed of two hydrogen atoms and one oxygen atom, giving it the chemical formula H2O.',NULL,'published'),
  ('GI060','General Information','General Information','General Science','General Information','Which planet in the solar system is closest to the Sun?',ARRAY['Venus','Earth','Mercury','Mars'],2,'Mercury is the smallest planet and the closest to the Sun in our solar system.',NULL,'published'),
  ('GI061','General Information','General Information','General Science','General Information','Which organelle is commonly known as the powerhouse of the cell?',ARRAY['Nucleus','Mitochondria','Ribosome','Golgi apparatus'],1,'Mitochondria generate most of a cell''s supply of ATP, which is why they are called the powerhouse of the cell.',NULL,'published'),
  ('GI062','General Information','General Information','General Science','General Information','Approximately how fast does light travel in a vacuum?',ARRAY['About 300,000 kilometers per second','About 300,000 kilometers per hour','About 30,000 kilometers per second','About 3,000 kilometers per second'],0,'Light travels at approximately 300,000 kilometers per second (299,792 km/s) in a vacuum.',NULL,'published'),
  ('GI063','General Information','General Information','General Science','General Information','Which gas do plants primarily absorb from the air during photosynthesis?',ARRAY['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'],2,'Plants absorb carbon dioxide and use sunlight to convert it, along with water, into glucose and oxygen during photosynthesis.',NULL,'published'),
  ('GI064','General Information','General Information','General Science','General Information','What is the basic unit of heredity that carries genetic information from parent to offspring?',ARRAY['Cell','Gene','Protein','Chromosome pair'],1,'A gene is the basic unit of heredity, made of DNA, that carries instructions passed from parents to offspring.',NULL,'published'),
  ('GI065','General Information','General Information','General Science','General Information','What is the force that pulls objects toward the center of the Earth?',ARRAY['Magnetism','Friction','Gravity','Tension'],2,'Gravity is the force of attraction that pulls objects toward the Earth''s center.',NULL,'published')
ON CONFLICT (question_id) DO NOTHING;
